/*
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.sdk.margin;

import static java.util.stream.Collectors.joining;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.joda.beans.impl.direct.DirectPrivateBeanBuilder;

/**
 * Portfolio data to pass to the service.
 */
@BeanDefinition(builderScope = "private", metaScope = "private")
public final class PortfolioDataFile implements ImmutableBean {

  /**
   * The portfolio name.
   */
  @PropertyDefinition(validate = "notNull")
  private final String name;
  /**
   * The portfolio data.
   */
  @PropertyDefinition(validate = "notNull")
  private final String data;

  //-------------------------------------------------------------------------
  /**
   * Obtains an instance.
   * 
   * @param name  the name, not empty
   * @param data  the data, not empty
   * @return the instance
   */
  public static PortfolioDataFile of(String name, String data) {
    return new PortfolioDataFile(name, data);
  }

  /**
   * Obtains an instance from a file.
   * 
   * @param path  the file
   * @return the instance
   */
  public static PortfolioDataFile of(Path path) {
    try {
      String data = Files.lines(path, StandardCharsets.UTF_8).collect(joining("\n"));
      return new PortfolioDataFile(path.getFileName().toString(), data);
    } catch (IOException ex) {
      throw new IllegalStateException(
          "IOException processing file: " + path.getFileName().toString() + ": " + ex.getMessage(), ex);
    }
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code PortfolioDataFile}.
   * @return the meta-bean, not null
   */
  public static MetaBean meta() {
    return PortfolioDataFile.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(PortfolioDataFile.Meta.INSTANCE);
  }

  private PortfolioDataFile(
      String name,
      String data) {
    JodaBeanUtils.notNull(name, "name");
    JodaBeanUtils.notNull(data, "data");
    this.name = name;
    this.data = data;
  }

  @Override
  public MetaBean metaBean() {
    return PortfolioDataFile.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the portfolio name.
   * @return the value of the property, not null
   */
  public String getName() {
    return name;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the portfolio data.
   * @return the value of the property, not null
   */
  public String getData() {
    return data;
  }

  //-----------------------------------------------------------------------
  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      PortfolioDataFile other = (PortfolioDataFile) obj;
      return JodaBeanUtils.equal(name, other.name) &&
          JodaBeanUtils.equal(data, other.data);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(name);
    hash = hash * 31 + JodaBeanUtils.hashCode(data);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(96);
    buf.append("PortfolioDataFile{");
    buf.append("name").append('=').append(name).append(',').append(' ');
    buf.append("data").append('=').append(JodaBeanUtils.toString(data));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code PortfolioDataFile}.
   */
  private static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code name} property.
     */
    private final MetaProperty<String> name = DirectMetaProperty.ofImmutable(
        this, "name", PortfolioDataFile.class, String.class);
    /**
     * The meta-property for the {@code data} property.
     */
    private final MetaProperty<String> data = DirectMetaProperty.ofImmutable(
        this, "data", PortfolioDataFile.class, String.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "name",
        "data");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 3373707:  // name
          return name;
        case 3076010:  // data
          return data;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends PortfolioDataFile> builder() {
      return new PortfolioDataFile.Builder();
    }

    @Override
    public Class<? extends PortfolioDataFile> beanType() {
      return PortfolioDataFile.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 3373707:  // name
          return ((PortfolioDataFile) bean).getName();
        case 3076010:  // data
          return ((PortfolioDataFile) bean).getData();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code PortfolioDataFile}.
   */
  private static final class Builder extends DirectPrivateBeanBuilder<PortfolioDataFile> {

    private String name;
    private String data;

    /**
     * Restricted constructor.
     */
    private Builder() {
      super(meta());
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 3373707:  // name
          return name;
        case 3076010:  // data
          return data;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 3373707:  // name
          this.name = (String) newValue;
          break;
        case 3076010:  // data
          this.data = (String) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public PortfolioDataFile build() {
      return new PortfolioDataFile(
          name,
          data);
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(96);
      buf.append("PortfolioDataFile.Builder{");
      buf.append("name").append('=').append(JodaBeanUtils.toString(name)).append(',').append(' ');
      buf.append("data").append('=').append(JodaBeanUtils.toString(data));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
